# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/86156/Desktop/calab/calab-68/Cooperative_project/prj6_exp17/mycpu_env/module_verify/tlb_verify/rtl/xilinx_ip/clk_pll.xci
# IP: The module: 'clk_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/86156/Desktop/calab/calab-68/Cooperative_project/prj6_exp17/mycpu_env/module_verify/tlb_verify/rtl/xilinx_ip/clk_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/86156/Desktop/calab/calab-68/Cooperative_project/prj6_exp17/mycpu_env/module_verify/tlb_verify/rtl/xilinx_ip/clk_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/86156/Desktop/calab/calab-68/Cooperative_project/prj6_exp17/mycpu_env/module_verify/tlb_verify/rtl/xilinx_ip/clk_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/86156/Desktop/calab/calab-68/Cooperative_project/prj6_exp17/mycpu_env/module_verify/tlb_verify/rtl/xilinx_ip/clk_pll.xci
# IP: The module: 'clk_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/86156/Desktop/calab/calab-68/Cooperative_project/prj6_exp17/mycpu_env/module_verify/tlb_verify/rtl/xilinx_ip/clk_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/86156/Desktop/calab/calab-68/Cooperative_project/prj6_exp17/mycpu_env/module_verify/tlb_verify/rtl/xilinx_ip/clk_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/86156/Desktop/calab/calab-68/Cooperative_project/prj6_exp17/mycpu_env/module_verify/tlb_verify/rtl/xilinx_ip/clk_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
